#!/usr/bin/env python
"""Fetch open sources for the first EML proof-lab audit."""

from __future__ import annotations

import datetime as dt
import hashlib
import shutil
import subprocess
import sys
import tarfile
from pathlib import Path
from urllib.request import urlretrieve


ROOT = Path(__file__).resolve().parents[1]
SOURCES = ROOT / "sources"
EXTERNAL = ROOT / "external"


DOWNLOADS = [
    (
        "arXiv paper v2 PDF",
        "https://arxiv.org/pdf/2603.21852v2",
        SOURCES / "2603.21852v2.pdf",
        "Main paper; Table 1 target and stated constructive claims.",
    ),
    (
        "arXiv e-print source bundle v2",
        "https://arxiv.org/e-print/2603.21852v2",
        SOURCES / "2603.21852v2.e-print.tar",
        "Source/ancillary archive; expected place to audit supplementary information links/files.",
    ),
    (
        "Hardware-Efficient Neuro-Symbolic Networks with the Exp-Minus-Log Operator",
        "https://arxiv.org/pdf/2604.13871",
        SOURCES / "2604.13871.pdf",
        "Follow-up EML hardware/neuro-symbolic paper; useful context, not proof evidence for Table 1.",
    ),
    (
        "Evaluating the Exp-Minus-Log Sheffer Operator for Battery Characterization",
        "https://arxiv.org/pdf/2604.13873",
        SOURCES / "2604.13873.pdf",
        "Follow-up applied EML paper; useful context, not proof evidence for Table 1.",
    ),
    (
        "Zenodo v1.0 snapshot zip",
        "https://zenodo.org/records/19183008/files/VA00/SymbolicRegressionPackage-v1.0.zip?download=1",
        SOURCES / "SymbolicRegressionPackage-v1.0.zip",
        "Archival software snapshot linked to the author code record.",
    ),
]


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def run(cmd: list[str], cwd: Path) -> str:
    completed = subprocess.run(cmd, cwd=cwd, check=False, text=True, capture_output=True)
    if completed.returncode != 0:
        raise RuntimeError(
            f"command failed: {' '.join(cmd)}\nSTDOUT:\n{completed.stdout}\nSTDERR:\n{completed.stderr}"
        )
    return completed.stdout.strip()


def fetch() -> list[dict[str, str]]:
    SOURCES.mkdir(exist_ok=True)
    EXTERNAL.mkdir(exist_ok=True)
    accessed = dt.date.today().isoformat()
    records: list[dict[str, str]] = []

    for title, url, path, why in DOWNLOADS:
        if not path.exists():
            print(f"downloading {url}")
            urlretrieve(url, path)
        records.append(
            {
                "title": title,
                "url": url,
                "date_accessed": accessed,
                "version": "v2" if "2603.21852" in url else "v1.0",
                "local": str(path.relative_to(ROOT)),
                "sha256": sha256(path),
                "why": why,
            }
        )

    si_path = SOURCES / "SupplementaryInformation.pdf"
    if not si_path.exists():
        with tarfile.open(SOURCES / "2603.21852v2.e-print.tar") as archive:
            member = archive.getmember("anc/SupplementaryInformation.pdf")
            with archive.extractfile(member) as src, si_path.open("wb") as dst:
                if src is None:
                    raise RuntimeError("anc/SupplementaryInformation.pdf missing from e-print archive")
                shutil.copyfileobj(src, dst)
    records.append(
        {
            "title": "SupplementaryInformation.pdf",
            "url": "https://arxiv.org/e-print/2603.21852v2 (anc/SupplementaryInformation.pdf)",
            "date_accessed": accessed,
            "version": "v2 ancillary",
            "local": str(si_path.relative_to(ROOT)),
            "sha256": sha256(si_path),
            "why": "Supplementary verification chain and formulas; required before full Table 1 success claims.",
        }
    )

    repo = EXTERNAL / "SymbolicRegressionPackage"
    if not repo.exists():
        run(["git", "clone", "https://github.com/VA00/SymbolicRegressionPackage.git", str(repo)], ROOT)
    else:
        run(["git", "fetch", "--all", "--tags"], repo)
    commit = run(["git", "rev-parse", "HEAD"], repo)
    records.append(
        {
            "title": "VA00/SymbolicRegressionPackage GitHub repository",
            "url": "https://github.com/VA00/SymbolicRegressionPackage",
            "date_accessed": accessed,
            "version": commit,
            "local": str(repo.relative_to(ROOT)),
            "sha256": "git-commit-" + commit,
            "why": "Author code with EML_toolkit, search tooling, and rust_verify reproduction targets.",
        }
    )

    return records


def write_manifest(records: list[dict[str, str]]) -> None:
    lines = [
        "# Source Manifest",
        "",
        "Generated by `scripts/bootstrap_sources.py`.",
        "",
    ]
    for item in records:
        lines.extend(
            [
                f"## {item['title']}",
                "",
                f"- URL: {item['url']}",
                f"- Date accessed: {item['date_accessed']}",
                f"- Version: {item['version']}",
                f"- Local path: `{item['local']}`",
                f"- SHA256/hash: `{item['sha256']}`",
                f"- Use: {item['why']}",
                "",
            ]
        )
    (SOURCES / "manifest.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    if shutil.which("git") is None:
        print("git is required", file=sys.stderr)
        return 2
    records = fetch()
    write_manifest(records)
    print(f"wrote {SOURCES / 'manifest.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
